//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACMaster
    {
        public ACMaster()
        {
            this.ACServiceHistories = new HashSet<ACServiceHistory>();
        }
    
        public int Id { get; set; }
        public int ACTypeMasterId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> LastServiceDate { get; set; }
        public string Note { get; set; }
        public int LocationMasterId { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> LastServiceId { get; set; }
    
        public virtual ACTypeMaster ACTypeMaster { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual ICollection<ACServiceHistory> ACServiceHistories { get; set; }
    }
}
