//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTypeMaster
    {
        public ACTypeMaster()
        {
            this.ACMasters = new HashSet<ACMaster>();
        }
    
        public int Id { get; set; }
        public string ACName { get; set; }
        public string ACCompanyName { get; set; }
        public decimal Tons { get; set; }
    
        public virtual ICollection<ACMaster> ACMasters { get; set; }
    }
}
