//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APM_ACMaintanceEntities : DbContext
    {
        public APM_ACMaintanceEntities()
            : base("name=APM_ACMaintanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACMaster> ACMasters { get; set; }
        public virtual DbSet<ACTypeMaster> ACTypeMasters { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<PersonMaster> PersonMasters { get; set; }
        public virtual DbSet<ACServiceHistory> ACServiceHistories { get; set; }
    }
}
